### ISSUE TITLE
Spellcheck?

### ISSUE THREAD

**Issue by jeremytiki** [sn-extensions/markdown-basic#10]
Is there any chance spellcheck could be added to this editor? Definitely my favourite, but this is the only draw back.

**Comment by mobitar** [comment]
Spellcheck can't be added per editor, as far as I know currently. Only plain editor.

**Comment by TheodoreChu** [comment]
I think as of v3.4, spellcheck for Markdown Basic is available on all platforms, but we can add spellcheck=true to the <textarea>
