### ISSUE TITLE
Enable Spellcheck in Desktop App

### ISSUE THREAD

**Issue by christianhans** [sn-extensions/markdown-basic#19]
On iOS the Edit view supports spell check. Is it possible to enable Spell check in the Desktop app as well? After all the Edit view is probably just a simple TextArea?

**Comment by mobitar** [comment]
I haven't found a way for Electron to enable spellcheck in an iframe.

**Comment by christianhans** [comment]
Does this help?

https://github.com/electron/electron/issues/13514

**Comment by mobitar** [comment]
Oo nice find! I was able to get that working for some of the editors, but not all of them. The two that didn't work were Advanced MD and Minimal MD. I'll have to play around with this a little more.

**Comment by christianhans** [comment]
Those don’t seem to support Spellcheck on iOS either.

**Comment by mobitar** [comment]
Oh it might be CodeMirror based editors actually. Usually those behave in tandem.

**Comment by christianhans** [comment]
It seems like EasyMDE behind the Advanced Markdown Editor supports spell check according to [its documentation](https://github.com/Ionaru/easy-markdown-editor). Can extensions check whether spell check in Standard Notes is enabled globally and then toggle Spellcheck within their component?

**Comment by mobitar** [comment]
It does support its own spellcheck, but last we had this enabled it was a real troublemaker. I wish I remember what the exact reason was. But it might be worth revisiting.

**Comment by TheodoreChu** [comment]
I think as of v3.4, spellcheck for Markdown Basic is available on all platforms, but we can add spellcheck=true to the `<textarea>`
