### ISSUE TITLE
Table background color

### ISSUE THREAD

**Issue by christianhans** [sn-extensions/markdown-basic#21]
Tables less wide than the window's width have a small problem with background color:

<img width="632" alt="Screen Shot 2019-06-02 at 07 26 15" src="https://user-images.githubusercontent.com/355541/58760572-bc2f6a00-8507-11e9-9793-c500a4754f2f.png">

**Comment by mobitar** [comment]
Can you share the raw markdown for this?

**Comment by christianhans** [comment]
```
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

| ffdf | dssdd | dsfff |
| ---- | -----  | --- |
| dsddadasd | fsfsf | sdd |
```

**Comment by mobitar** [comment]
This might need bg coloring of the rows and cells instead of the whole table.

**Comment by TheodoreChu** [comment]
This is fixed in upcoming PR
